# Site settings
title: 현재 사이트는 수정중입니다.
baseurl: ""
url: "https://soduma.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: KIHWA JANG
  desc: Hello nice to meet you
  email: soduma2@gmail.com
  selfie: assets/img/profile.jpeg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: soduma
  google_plus:
  instagram: infofield
  keybase:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
